//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OAD.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderItems
    {
        public int order_num { get; set; }
        public int order_item { get; set; }
        public string prod_id { get; set; }
        public int quantity { get; set; }
        public decimal item_price { get; set; }
    
        public virtual Orders Orders { get; set; }
        public virtual Products Products { get; set; }
    }
}
