//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OAD.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vendors
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Vendors()
        {
            this.Products = new HashSet<Products>();
        }
    
        public string vend_id { get; set; }
        public string vend_name { get; set; }
        public string vend_address { get; set; }
        public string vend_city { get; set; }
        public string vend_state { get; set; }
        public string vend_zip { get; set; }
        public string vend_country { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Products> Products { get; set; }
    }
}
